version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "tuesday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "pubky/pubky"
      - dependency-name: "pubky/pubky-common"
      - dependency-name: "pubky/pubky-homeserver"
      - directory: "/pubky"
