[package]
name = "pk-social-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
axum = "0.7.5"

[dev-dependencies]
anyhow = "1.0.86"
httpc-test = "0.1.9"
